services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    tty: true
    env_file:
      - .env
volumes:
  database: