services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/local/src/app
    ports:
      - 8080:8080
    tty: true
    environment:
      PORT: 8080
      VERSION: 0.0.1
      ENV: development
      DISCORD_TOKEN:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"