version: 1
formatters:
  generic:
    class: logging.Formatter
    format: '%(asctime)s %(name)s %(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: generic
    stream: ext://sys.stdout
loggers:
  waitress:
    level: INFO
root:
  level: DEBUG
  handlers:
    - console