version: '3.9'
services:
  database:
    container_name: tsukuyomi_db_test
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/test/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
  server:
    container_name: tsukuyomi_server_test
    build:
      context: .
      dockerfile: build/tsukuyomi/Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - ENV_MODE=test
#  nginx:
#    build: nginx/.
#    depends_on:
#      - application
#    ports:
#      - "8080:80"
#    volumes:
#      - ./.docker/test/nginx:/u