version: '3.9'
services:
  database:
    container_name: tsukuyomi_db_test
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/test/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 10
  server:
    container_name: tsukuyomi_server_test
    build: .
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - ENV_MODE=test
      - VERSION=dev
      - PORT=8080
      - DATABASE_HOST=tsukuyomi_db_test
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_SSLMODE=disable
      - DISCORD_TOKEN=
      - LINEBOT_SECRET_KEY=
      - LINEBOT_CHANNEL_ACCESS_TOKEN=
      - GOOGLE_API_KEY=
#  nginx:
#    build: nginx/.
#    depends_on:
#      - application
#    ports:
#      - "8080:80"
#    volumes:
#      - ./.docker/test/nginx:/u