# fly.toml app configuration file generated for tsukuyomi on 2023-06-03T01:36:23+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tsukuyomi"
primary_region = "nrt"

[env]
  ENV = "production"
  PORT = "8080"
  VERSION = "0.0.1"

[[services]]
  protocol = ""
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1
    soft_limit = 1

  [[services.http_checks]]
    interval = "10s"
    timeout = "30s"
    grace_period = "30s"
    restart_limit = 10
    method = "get"
    path = "/version"
    protocol = "http"
