# fly.toml app configuration file generated for tsukuyomi on 2023-05-26T15:43:02+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tsukuyomi"
primary_region = "nrt"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.name_of_your_http_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/version"
    port = 8080
    timeout = "10s"
    type = "http"

[env]
  VERSION = "0.0.1"
  ENV = "production"
  PORT = 8080
