// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"tsukuyomi/ent/lineuser"
	"tsukuyomi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineUserQuery is the builder for querying LineUser entities.
type LineUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LineUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LineUserQuery builder.
func (luq *LineUserQuery) Where(ps ...predicate.LineUser) *LineUserQuery {
	luq.predicates = append(luq.predicates, ps...)
	return luq
}

// Limit adds a limit step to the query.
func (luq *LineUserQuery) Limit(limit int) *LineUserQuery {
	luq.limit = &limit
	return luq
}

// Offset adds an offset step to the query.
func (luq *LineUserQuery) Offset(offset int) *LineUserQuery {
	luq.offset = &offset
	return luq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (luq *LineUserQuery) Unique(unique bool) *LineUserQuery {
	luq.unique = &unique
	return luq
}

// Order adds an order step to the query.
func (luq *LineUserQuery) Order(o ...OrderFunc) *LineUserQuery {
	luq.order = append(luq.order, o...)
	return luq
}

// First returns the first LineUser entity from the query.
// Returns a *NotFoundError when no LineUser was found.
func (luq *LineUserQuery) First(ctx context.Context) (*LineUser, error) {
	nodes, err := luq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lineuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (luq *LineUserQuery) FirstX(ctx context.Context) *LineUser {
	node, err := luq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LineUser ID from the query.
// Returns a *NotFoundError when no LineUser ID was found.
func (luq *LineUserQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = luq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lineuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (luq *LineUserQuery) FirstIDX(ctx context.Context) string {
	id, err := luq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LineUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LineUser entity is found.
// Returns a *NotFoundError when no LineUser entities are found.
func (luq *LineUserQuery) Only(ctx context.Context) (*LineUser, error) {
	nodes, err := luq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lineuser.Label}
	default:
		return nil, &NotSingularError{lineuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (luq *LineUserQuery) OnlyX(ctx context.Context) *LineUser {
	node, err := luq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LineUser ID in the query.
// Returns a *NotSingularError when more than one LineUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (luq *LineUserQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = luq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lineuser.Label}
	default:
		err = &NotSingularError{lineuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (luq *LineUserQuery) OnlyIDX(ctx context.Context) string {
	id, err := luq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LineUsers.
func (luq *LineUserQuery) All(ctx context.Context) ([]*LineUser, error) {
	if err := luq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return luq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (luq *LineUserQuery) AllX(ctx context.Context) []*LineUser {
	nodes, err := luq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LineUser IDs.
func (luq *LineUserQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := luq.Select(lineuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (luq *LineUserQuery) IDsX(ctx context.Context) []string {
	ids, err := luq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (luq *LineUserQuery) Count(ctx context.Context) (int, error) {
	if err := luq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return luq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (luq *LineUserQuery) CountX(ctx context.Context) int {
	count, err := luq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (luq *LineUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := luq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return luq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (luq *LineUserQuery) ExistX(ctx context.Context) bool {
	exist, err := luq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LineUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (luq *LineUserQuery) Clone() *LineUserQuery {
	if luq == nil {
		return nil
	}
	return &LineUserQuery{
		config:     luq.config,
		limit:      luq.limit,
		offset:     luq.offset,
		order:      append([]OrderFunc{}, luq.order...),
		predicates: append([]predicate.LineUser{}, luq.predicates...),
		// clone intermediate query.
		sql:    luq.sql.Clone(),
		path:   luq.path,
		unique: luq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IsActive bool `json:"is_active,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LineUser.Query().
//		GroupBy(lineuser.FieldIsActive).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (luq *LineUserQuery) GroupBy(field string, fields ...string) *LineUserGroupBy {
	group := &LineUserGroupBy{config: luq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := luq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return luq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IsActive bool `json:"is_active,omitempty"`
//	}
//
//	client.LineUser.Query().
//		Select(lineuser.FieldIsActive).
//		Scan(ctx, &v)
//
func (luq *LineUserQuery) Select(fields ...string) *LineUserSelect {
	luq.fields = append(luq.fields, fields...)
	return &LineUserSelect{LineUserQuery: luq}
}

func (luq *LineUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range luq.fields {
		if !lineuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if luq.path != nil {
		prev, err := luq.path(ctx)
		if err != nil {
			return err
		}
		luq.sql = prev
	}
	return nil
}

func (luq *LineUserQuery) sqlAll(ctx context.Context) ([]*LineUser, error) {
	var (
		nodes = []*LineUser{}
		_spec = luq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LineUser{config: luq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, luq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (luq *LineUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := luq.querySpec()
	_spec.Node.Columns = luq.fields
	if len(luq.fields) > 0 {
		_spec.Unique = luq.unique != nil && *luq.unique
	}
	return sqlgraph.CountNodes(ctx, luq.driver, _spec)
}

func (luq *LineUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := luq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (luq *LineUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lineuser.Table,
			Columns: lineuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: lineuser.FieldID,
			},
		},
		From:   luq.sql,
		Unique: true,
	}
	if unique := luq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := luq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lineuser.FieldID)
		for i := range fields {
			if fields[i] != lineuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := luq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := luq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := luq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := luq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (luq *LineUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(luq.driver.Dialect())
	t1 := builder.Table(lineuser.Table)
	columns := luq.fields
	if len(columns) == 0 {
		columns = lineuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if luq.sql != nil {
		selector = luq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if luq.unique != nil && *luq.unique {
		selector.Distinct()
	}
	for _, p := range luq.predicates {
		p(selector)
	}
	for _, p := range luq.order {
		p(selector)
	}
	if offset := luq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := luq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LineUserGroupBy is the group-by builder for LineUser entities.
type LineUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lugb *LineUserGroupBy) Aggregate(fns ...AggregateFunc) *LineUserGroupBy {
	lugb.fns = append(lugb.fns, fns...)
	return lugb
}

// Scan applies the group-by query and scans the result into the given value.
func (lugb *LineUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := lugb.path(ctx)
	if err != nil {
		return err
	}
	lugb.sql = query
	return lugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lugb *LineUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := lugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (lugb *LineUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(lugb.fields) > 1 {
		return nil, errors.New("ent: LineUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := lugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lugb *LineUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := lugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lugb *LineUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lineuser.Label}
	default:
		err = fmt.Errorf("ent: LineUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lugb *LineUserGroupBy) StringX(ctx context.Context) string {
	v, err := lugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (lugb *LineUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(lugb.fields) > 1 {
		return nil, errors.New("ent: LineUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := lugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lugb *LineUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := lugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lugb *LineUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lineuser.Label}
	default:
		err = fmt.Errorf("ent: LineUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lugb *LineUserGroupBy) IntX(ctx context.Context) int {
	v, err := lugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (lugb *LineUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(lugb.fields) > 1 {
		return nil, errors.New("ent: LineUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := lugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lugb *LineUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := lugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lugb *LineUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lineuser.Label}
	default:
		err = fmt.Errorf("ent: LineUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lugb *LineUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := lugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (lugb *LineUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(lugb.fields) > 1 {
		return nil, errors.New("ent: LineUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := lugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lugb *LineUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := lugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lugb *LineUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lineuser.Label}
	default:
		err = fmt.Errorf("ent: LineUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lugb *LineUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := lugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lugb *LineUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range lugb.fields {
		if !lineuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lugb *LineUserGroupBy) sqlQuery() *sql.Selector {
	selector := lugb.sql.Select()
	aggregation := make([]string, 0, len(lugb.fns))
	for _, fn := range lugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(lugb.fields)+len(lugb.fns))
		for _, f := range lugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(lugb.fields...)...)
}

// LineUserSelect is the builder for selecting fields of LineUser entities.
type LineUserSelect struct {
	*LineUserQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lus *LineUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lus.prepareQuery(ctx); err != nil {
		return err
	}
	lus.sql = lus.LineUserQuery.sqlQuery(ctx)
	return lus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lus *LineUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := lus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lus *LineUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(lus.fields) > 1 {
		return nil, errors.New("ent: LineUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lus *LineUserSelect) StringsX(ctx context.Context) []string {
	v, err := lus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lus *LineUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lineuser.Label}
	default:
		err = fmt.Errorf("ent: LineUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lus *LineUserSelect) StringX(ctx context.Context) string {
	v, err := lus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lus *LineUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(lus.fields) > 1 {
		return nil, errors.New("ent: LineUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lus *LineUserSelect) IntsX(ctx context.Context) []int {
	v, err := lus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lus *LineUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lineuser.Label}
	default:
		err = fmt.Errorf("ent: LineUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lus *LineUserSelect) IntX(ctx context.Context) int {
	v, err := lus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lus *LineUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lus.fields) > 1 {
		return nil, errors.New("ent: LineUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lus *LineUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := lus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lus *LineUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lineuser.Label}
	default:
		err = fmt.Errorf("ent: LineUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lus *LineUserSelect) Float64X(ctx context.Context) float64 {
	v, err := lus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lus *LineUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lus.fields) > 1 {
		return nil, errors.New("ent: LineUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lus *LineUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := lus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lus *LineUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lineuser.Label}
	default:
		err = fmt.Errorf("ent: LineUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lus *LineUserSelect) BoolX(ctx context.Context) bool {
	v, err := lus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lus *LineUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lus.sql.Query()
	if err := lus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
