// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"tsukuyomi/ent/lineuser"

	"entgo.io/ent/dialect/sql"
)

// LineUser is the model entity for the LineUser schema.
type LineUser struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreateAt holds the value of the "create_at" field.
	CreateAt time.Time `json:"create_at,omitempty"`
	// UpdateAt holds the value of the "update_at" field.
	UpdateAt time.Time `json:"update_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LineUser) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case lineuser.FieldIsActive:
			values[i] = new(sql.NullBool)
		case lineuser.FieldID:
			values[i] = new(sql.NullString)
		case lineuser.FieldCreateAt, lineuser.FieldUpdateAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type LineUser", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LineUser fields.
func (lu *LineUser) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case lineuser.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				lu.ID = value.String
			}
		case lineuser.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				lu.IsActive = value.Bool
			}
		case lineuser.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				lu.CreateAt = value.Time
			}
		case lineuser.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				lu.UpdateAt = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this LineUser.
// Note that you need to call LineUser.Unwrap() before calling this method if this LineUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (lu *LineUser) Update() *LineUserUpdateOne {
	return (&LineUserClient{config: lu.config}).UpdateOne(lu)
}

// Unwrap unwraps the LineUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lu *LineUser) Unwrap() *LineUser {
	tx, ok := lu.config.driver.(*txDriver)
	if !ok {
		panic("ent: LineUser is not a transactional entity")
	}
	lu.config.driver = tx.drv
	return lu
}

// String implements the fmt.Stringer.
func (lu *LineUser) String() string {
	var builder strings.Builder
	builder.WriteString("LineUser(")
	builder.WriteString(fmt.Sprintf("id=%v", lu.ID))
	builder.WriteString(", is_active=")
	builder.WriteString(fmt.Sprintf("%v", lu.IsActive))
	builder.WriteString(", create_at=")
	builder.WriteString(lu.CreateAt.Format(time.ANSIC))
	builder.WriteString(", update_at=")
	builder.WriteString(lu.UpdateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LineUsers is a parsable slice of LineUser.
type LineUsers []*LineUser

func (lu LineUsers) config(cfg config) {
	for _i := range lu {
		lu[_i].config = cfg
	}
}
