// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LineUsersColumns holds the columns for the "line_users" table.
	LineUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "create_at", Type: field.TypeTime},
		{Name: "update_at", Type: field.TypeTime},
	}
	// LineUsersTable holds the schema information for the "line_users" table.
	LineUsersTable = &schema.Table{
		Name:       "line_users",
		Columns:    LineUsersColumns,
		PrimaryKey: []*schema.Column{LineUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LineUsersTable,
	}
)

func init() {
}
