// Code generated by entc, DO NOT EDIT.

package replysession

import (
	"time"
)

const (
	// Label holds the string label denoting the replysession type in the database.
	Label = "reply_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateAt holds the string denoting the create_at field in the database.
	FieldCreateAt = "create_at"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// Table holds the table name of the replysession in the database.
	Table = "reply_sessions"
)

// Columns holds all SQL columns for replysession fields.
var Columns = []string{
	FieldID,
	FieldCreateAt,
	FieldType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateAt holds the default value on creation for the "create_at" field.
	DefaultCreateAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)
