// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"tsukuyomi/ent/migrate"

	"tsukuyomi/ent/linesession"
	"tsukuyomi/ent/lineuser"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// LineSession is the client for interacting with the LineSession builders.
	LineSession *LineSessionClient
	// LineUser is the client for interacting with the LineUser builders.
	LineUser *LineUserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.LineSession = NewLineSessionClient(c.config)
	c.LineUser = NewLineUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		LineSession: NewLineSessionClient(cfg),
		LineUser:    NewLineUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		LineSession: NewLineSessionClient(cfg),
		LineUser:    NewLineUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		LineSession.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.LineSession.Use(hooks...)
	c.LineUser.Use(hooks...)
}

// LineSessionClient is a client for the LineSession schema.
type LineSessionClient struct {
	config
}

// NewLineSessionClient returns a client for the LineSession from the given config.
func NewLineSessionClient(c config) *LineSessionClient {
	return &LineSessionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `linesession.Hooks(f(g(h())))`.
func (c *LineSessionClient) Use(hooks ...Hook) {
	c.hooks.LineSession = append(c.hooks.LineSession, hooks...)
}

// Create returns a create builder for LineSession.
func (c *LineSessionClient) Create() *LineSessionCreate {
	mutation := newLineSessionMutation(c.config, OpCreate)
	return &LineSessionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LineSession entities.
func (c *LineSessionClient) CreateBulk(builders ...*LineSessionCreate) *LineSessionCreateBulk {
	return &LineSessionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LineSession.
func (c *LineSessionClient) Update() *LineSessionUpdate {
	mutation := newLineSessionMutation(c.config, OpUpdate)
	return &LineSessionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LineSessionClient) UpdateOne(ls *LineSession) *LineSessionUpdateOne {
	mutation := newLineSessionMutation(c.config, OpUpdateOne, withLineSession(ls))
	return &LineSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LineSessionClient) UpdateOneID(id int) *LineSessionUpdateOne {
	mutation := newLineSessionMutation(c.config, OpUpdateOne, withLineSessionID(id))
	return &LineSessionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LineSession.
func (c *LineSessionClient) Delete() *LineSessionDelete {
	mutation := newLineSessionMutation(c.config, OpDelete)
	return &LineSessionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *LineSessionClient) DeleteOne(ls *LineSession) *LineSessionDeleteOne {
	return c.DeleteOneID(ls.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *LineSessionClient) DeleteOneID(id int) *LineSessionDeleteOne {
	builder := c.Delete().Where(linesession.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LineSessionDeleteOne{builder}
}

// Query returns a query builder for LineSession.
func (c *LineSessionClient) Query() *LineSessionQuery {
	return &LineSessionQuery{
		config: c.config,
	}
}

// Get returns a LineSession entity by its id.
func (c *LineSessionClient) Get(ctx context.Context, id int) (*LineSession, error) {
	return c.Query().Where(linesession.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LineSessionClient) GetX(ctx context.Context, id int) *LineSession {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LineSessionClient) Hooks() []Hook {
	return c.hooks.LineSession
}

// LineUserClient is a client for the LineUser schema.
type LineUserClient struct {
	config
}

// NewLineUserClient returns a client for the LineUser from the given config.
func NewLineUserClient(c config) *LineUserClient {
	return &LineUserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lineuser.Hooks(f(g(h())))`.
func (c *LineUserClient) Use(hooks ...Hook) {
	c.hooks.LineUser = append(c.hooks.LineUser, hooks...)
}

// Create returns a create builder for LineUser.
func (c *LineUserClient) Create() *LineUserCreate {
	mutation := newLineUserMutation(c.config, OpCreate)
	return &LineUserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LineUser entities.
func (c *LineUserClient) CreateBulk(builders ...*LineUserCreate) *LineUserCreateBulk {
	return &LineUserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LineUser.
func (c *LineUserClient) Update() *LineUserUpdate {
	mutation := newLineUserMutation(c.config, OpUpdate)
	return &LineUserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LineUserClient) UpdateOne(lu *LineUser) *LineUserUpdateOne {
	mutation := newLineUserMutation(c.config, OpUpdateOne, withLineUser(lu))
	return &LineUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LineUserClient) UpdateOneID(id string) *LineUserUpdateOne {
	mutation := newLineUserMutation(c.config, OpUpdateOne, withLineUserID(id))
	return &LineUserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LineUser.
func (c *LineUserClient) Delete() *LineUserDelete {
	mutation := newLineUserMutation(c.config, OpDelete)
	return &LineUserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *LineUserClient) DeleteOne(lu *LineUser) *LineUserDeleteOne {
	return c.DeleteOneID(lu.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *LineUserClient) DeleteOneID(id string) *LineUserDeleteOne {
	builder := c.Delete().Where(lineuser.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LineUserDeleteOne{builder}
}

// Query returns a query builder for LineUser.
func (c *LineUserClient) Query() *LineUserQuery {
	return &LineUserQuery{
		config: c.config,
	}
}

// Get returns a LineUser entity by its id.
func (c *LineUserClient) Get(ctx context.Context, id string) (*LineUser, error) {
	return c.Query().Where(lineuser.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LineUserClient) GetX(ctx context.Context, id string) *LineUser {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LineUserClient) Hooks() []Hook {
	return c.hooks.LineUser
}
