// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tsukuyomi/ent/linesession"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineSessionCreate is the builder for creating a LineSession entity.
type LineSessionCreate struct {
	config
	mutation *LineSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetType sets the "type" field.
func (lsc *LineSessionCreate) SetType(i int8) *LineSessionCreate {
	lsc.mutation.SetType(i)
	return lsc
}

// SetUserID sets the "user_id" field.
func (lsc *LineSessionCreate) SetUserID(s string) *LineSessionCreate {
	lsc.mutation.SetUserID(s)
	return lsc
}

// SetGroupID sets the "group_id" field.
func (lsc *LineSessionCreate) SetGroupID(s string) *LineSessionCreate {
	lsc.mutation.SetGroupID(s)
	return lsc
}

// SetRoomID sets the "room_id" field.
func (lsc *LineSessionCreate) SetRoomID(s string) *LineSessionCreate {
	lsc.mutation.SetRoomID(s)
	return lsc
}

// SetCreateAt sets the "create_at" field.
func (lsc *LineSessionCreate) SetCreateAt(t time.Time) *LineSessionCreate {
	lsc.mutation.SetCreateAt(t)
	return lsc
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (lsc *LineSessionCreate) SetNillableCreateAt(t *time.Time) *LineSessionCreate {
	if t != nil {
		lsc.SetCreateAt(*t)
	}
	return lsc
}

// SetUpdateAt sets the "update_at" field.
func (lsc *LineSessionCreate) SetUpdateAt(t time.Time) *LineSessionCreate {
	lsc.mutation.SetUpdateAt(t)
	return lsc
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (lsc *LineSessionCreate) SetNillableUpdateAt(t *time.Time) *LineSessionCreate {
	if t != nil {
		lsc.SetUpdateAt(*t)
	}
	return lsc
}

// Mutation returns the LineSessionMutation object of the builder.
func (lsc *LineSessionCreate) Mutation() *LineSessionMutation {
	return lsc.mutation
}

// Save creates the LineSession in the database.
func (lsc *LineSessionCreate) Save(ctx context.Context) (*LineSession, error) {
	var (
		err  error
		node *LineSession
	)
	lsc.defaults()
	if len(lsc.hooks) == 0 {
		if err = lsc.check(); err != nil {
			return nil, err
		}
		node, err = lsc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LineSessionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = lsc.check(); err != nil {
				return nil, err
			}
			lsc.mutation = mutation
			if node, err = lsc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(lsc.hooks) - 1; i >= 0; i-- {
			if lsc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lsc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lsc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (lsc *LineSessionCreate) SaveX(ctx context.Context) *LineSession {
	v, err := lsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lsc *LineSessionCreate) Exec(ctx context.Context) error {
	_, err := lsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lsc *LineSessionCreate) ExecX(ctx context.Context) {
	if err := lsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (lsc *LineSessionCreate) defaults() {
	if _, ok := lsc.mutation.CreateAt(); !ok {
		v := linesession.DefaultCreateAt()
		lsc.mutation.SetCreateAt(v)
	}
	if _, ok := lsc.mutation.UpdateAt(); !ok {
		v := linesession.DefaultUpdateAt()
		lsc.mutation.SetUpdateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lsc *LineSessionCreate) check() error {
	if _, ok := lsc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "LineSession.type"`)}
	}
	if _, ok := lsc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LineSession.user_id"`)}
	}
	if v, ok := lsc.mutation.UserID(); ok {
		if err := linesession.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "LineSession.user_id": %w`, err)}
		}
	}
	if _, ok := lsc.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "LineSession.group_id"`)}
	}
	if v, ok := lsc.mutation.GroupID(); ok {
		if err := linesession.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "LineSession.group_id": %w`, err)}
		}
	}
	if _, ok := lsc.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "LineSession.room_id"`)}
	}
	if v, ok := lsc.mutation.RoomID(); ok {
		if err := linesession.RoomIDValidator(v); err != nil {
			return &ValidationError{Name: "room_id", err: fmt.Errorf(`ent: validator failed for field "LineSession.room_id": %w`, err)}
		}
	}
	if _, ok := lsc.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "LineSession.create_at"`)}
	}
	if _, ok := lsc.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "LineSession.update_at"`)}
	}
	return nil
}

func (lsc *LineSessionCreate) sqlSave(ctx context.Context) (*LineSession, error) {
	_node, _spec := lsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (lsc *LineSessionCreate) createSpec() (*LineSession, *sqlgraph.CreateSpec) {
	var (
		_node = &LineSession{config: lsc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: linesession.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: linesession.FieldID,
			},
		}
	)
	_spec.OnConflict = lsc.conflict
	if value, ok := lsc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: linesession.FieldType,
		})
		_node.Type = value
	}
	if value, ok := lsc.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: linesession.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := lsc.mutation.GroupID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: linesession.FieldGroupID,
		})
		_node.GroupID = value
	}
	if value, ok := lsc.mutation.RoomID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: linesession.FieldRoomID,
		})
		_node.RoomID = value
	}
	if value, ok := lsc.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: linesession.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := lsc.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: linesession.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LineSession.Create().
//		SetType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LineSessionUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
//
func (lsc *LineSessionCreate) OnConflict(opts ...sql.ConflictOption) *LineSessionUpsertOne {
	lsc.conflict = opts
	return &LineSessionUpsertOne{
		create: lsc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LineSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (lsc *LineSessionCreate) OnConflictColumns(columns ...string) *LineSessionUpsertOne {
	lsc.conflict = append(lsc.conflict, sql.ConflictColumns(columns...))
	return &LineSessionUpsertOne{
		create: lsc,
	}
}

type (
	// LineSessionUpsertOne is the builder for "upsert"-ing
	//  one LineSession node.
	LineSessionUpsertOne struct {
		create *LineSessionCreate
	}

	// LineSessionUpsert is the "OnConflict" setter.
	LineSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetType sets the "type" field.
func (u *LineSessionUpsert) SetType(v int8) *LineSessionUpsert {
	u.Set(linesession.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *LineSessionUpsert) UpdateType() *LineSessionUpsert {
	u.SetExcluded(linesession.FieldType)
	return u
}

// AddType adds v to the "type" field.
func (u *LineSessionUpsert) AddType(v int8) *LineSessionUpsert {
	u.Add(linesession.FieldType, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LineSessionUpsert) SetUserID(v string) *LineSessionUpsert {
	u.Set(linesession.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LineSessionUpsert) UpdateUserID() *LineSessionUpsert {
	u.SetExcluded(linesession.FieldUserID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *LineSessionUpsert) SetGroupID(v string) *LineSessionUpsert {
	u.Set(linesession.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *LineSessionUpsert) UpdateGroupID() *LineSessionUpsert {
	u.SetExcluded(linesession.FieldGroupID)
	return u
}

// SetRoomID sets the "room_id" field.
func (u *LineSessionUpsert) SetRoomID(v string) *LineSessionUpsert {
	u.Set(linesession.FieldRoomID, v)
	return u
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *LineSessionUpsert) UpdateRoomID() *LineSessionUpsert {
	u.SetExcluded(linesession.FieldRoomID)
	return u
}

// SetCreateAt sets the "create_at" field.
func (u *LineSessionUpsert) SetCreateAt(v time.Time) *LineSessionUpsert {
	u.Set(linesession.FieldCreateAt, v)
	return u
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *LineSessionUpsert) UpdateCreateAt() *LineSessionUpsert {
	u.SetExcluded(linesession.FieldCreateAt)
	return u
}

// SetUpdateAt sets the "update_at" field.
func (u *LineSessionUpsert) SetUpdateAt(v time.Time) *LineSessionUpsert {
	u.Set(linesession.FieldUpdateAt, v)
	return u
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *LineSessionUpsert) UpdateUpdateAt() *LineSessionUpsert {
	u.SetExcluded(linesession.FieldUpdateAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LineSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *LineSessionUpsertOne) UpdateNewValues() *LineSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.GetType(); exists {
			s.SetIgnore(linesession.FieldType)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(linesession.FieldUserID)
		}
		if _, exists := u.create.mutation.GroupID(); exists {
			s.SetIgnore(linesession.FieldGroupID)
		}
		if _, exists := u.create.mutation.RoomID(); exists {
			s.SetIgnore(linesession.FieldRoomID)
		}
		if _, exists := u.create.mutation.CreateAt(); exists {
			s.SetIgnore(linesession.FieldCreateAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.LineSession.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *LineSessionUpsertOne) Ignore() *LineSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LineSessionUpsertOne) DoNothing() *LineSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LineSessionCreate.OnConflict
// documentation for more info.
func (u *LineSessionUpsertOne) Update(set func(*LineSessionUpsert)) *LineSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LineSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *LineSessionUpsertOne) SetType(v int8) *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *LineSessionUpsertOne) AddType(v int8) *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *LineSessionUpsertOne) UpdateType() *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateType()
	})
}

// SetUserID sets the "user_id" field.
func (u *LineSessionUpsertOne) SetUserID(v string) *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LineSessionUpsertOne) UpdateUserID() *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *LineSessionUpsertOne) SetGroupID(v string) *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *LineSessionUpsertOne) UpdateGroupID() *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateGroupID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *LineSessionUpsertOne) SetRoomID(v string) *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *LineSessionUpsertOne) UpdateRoomID() *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateRoomID()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *LineSessionUpsertOne) SetCreateAt(v time.Time) *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *LineSessionUpsertOne) UpdateCreateAt() *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *LineSessionUpsertOne) SetUpdateAt(v time.Time) *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *LineSessionUpsertOne) UpdateUpdateAt() *LineSessionUpsertOne {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateUpdateAt()
	})
}

// Exec executes the query.
func (u *LineSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LineSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LineSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LineSessionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LineSessionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LineSessionCreateBulk is the builder for creating many LineSession entities in bulk.
type LineSessionCreateBulk struct {
	config
	builders []*LineSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the LineSession entities in the database.
func (lscb *LineSessionCreateBulk) Save(ctx context.Context) ([]*LineSession, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lscb.builders))
	nodes := make([]*LineSession, len(lscb.builders))
	mutators := make([]Mutator, len(lscb.builders))
	for i := range lscb.builders {
		func(i int, root context.Context) {
			builder := lscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LineSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = lscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lscb *LineSessionCreateBulk) SaveX(ctx context.Context) []*LineSession {
	v, err := lscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lscb *LineSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := lscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lscb *LineSessionCreateBulk) ExecX(ctx context.Context) {
	if err := lscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LineSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LineSessionUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
//
func (lscb *LineSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *LineSessionUpsertBulk {
	lscb.conflict = opts
	return &LineSessionUpsertBulk{
		create: lscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LineSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (lscb *LineSessionCreateBulk) OnConflictColumns(columns ...string) *LineSessionUpsertBulk {
	lscb.conflict = append(lscb.conflict, sql.ConflictColumns(columns...))
	return &LineSessionUpsertBulk{
		create: lscb,
	}
}

// LineSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of LineSession nodes.
type LineSessionUpsertBulk struct {
	create *LineSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LineSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *LineSessionUpsertBulk) UpdateNewValues() *LineSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.GetType(); exists {
				s.SetIgnore(linesession.FieldType)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(linesession.FieldUserID)
			}
			if _, exists := b.mutation.GroupID(); exists {
				s.SetIgnore(linesession.FieldGroupID)
			}
			if _, exists := b.mutation.RoomID(); exists {
				s.SetIgnore(linesession.FieldRoomID)
			}
			if _, exists := b.mutation.CreateAt(); exists {
				s.SetIgnore(linesession.FieldCreateAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LineSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *LineSessionUpsertBulk) Ignore() *LineSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LineSessionUpsertBulk) DoNothing() *LineSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LineSessionCreateBulk.OnConflict
// documentation for more info.
func (u *LineSessionUpsertBulk) Update(set func(*LineSessionUpsert)) *LineSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LineSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *LineSessionUpsertBulk) SetType(v int8) *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *LineSessionUpsertBulk) AddType(v int8) *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *LineSessionUpsertBulk) UpdateType() *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateType()
	})
}

// SetUserID sets the "user_id" field.
func (u *LineSessionUpsertBulk) SetUserID(v string) *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LineSessionUpsertBulk) UpdateUserID() *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *LineSessionUpsertBulk) SetGroupID(v string) *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *LineSessionUpsertBulk) UpdateGroupID() *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateGroupID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *LineSessionUpsertBulk) SetRoomID(v string) *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *LineSessionUpsertBulk) UpdateRoomID() *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateRoomID()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *LineSessionUpsertBulk) SetCreateAt(v time.Time) *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *LineSessionUpsertBulk) UpdateCreateAt() *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *LineSessionUpsertBulk) SetUpdateAt(v time.Time) *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.SetUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *LineSessionUpsertBulk) UpdateUpdateAt() *LineSessionUpsertBulk {
	return u.Update(func(s *LineSessionUpsert) {
		s.UpdateUpdateAt()
	})
}

// Exec executes the query.
func (u *LineSessionUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LineSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LineSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LineSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
