// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tsukuyomi/ent/linesession"
	"tsukuyomi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineSessionUpdate is the builder for updating LineSession entities.
type LineSessionUpdate struct {
	config
	hooks    []Hook
	mutation *LineSessionMutation
}

// Where appends a list predicates to the LineSessionUpdate builder.
func (lsu *LineSessionUpdate) Where(ps ...predicate.LineSession) *LineSessionUpdate {
	lsu.mutation.Where(ps...)
	return lsu
}

// SetUpdateAt sets the "update_at" field.
func (lsu *LineSessionUpdate) SetUpdateAt(t time.Time) *LineSessionUpdate {
	lsu.mutation.SetUpdateAt(t)
	return lsu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (lsu *LineSessionUpdate) SetNillableUpdateAt(t *time.Time) *LineSessionUpdate {
	if t != nil {
		lsu.SetUpdateAt(*t)
	}
	return lsu
}

// Mutation returns the LineSessionMutation object of the builder.
func (lsu *LineSessionUpdate) Mutation() *LineSessionMutation {
	return lsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lsu *LineSessionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lsu.hooks) == 0 {
		affected, err = lsu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LineSessionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lsu.mutation = mutation
			affected, err = lsu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lsu.hooks) - 1; i >= 0; i-- {
			if lsu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lsu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lsu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (lsu *LineSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := lsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lsu *LineSessionUpdate) Exec(ctx context.Context) error {
	_, err := lsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lsu *LineSessionUpdate) ExecX(ctx context.Context) {
	if err := lsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lsu *LineSessionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   linesession.Table,
			Columns: linesession.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: linesession.FieldID,
			},
		},
	}
	if ps := lsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lsu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: linesession.FieldUpdateAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// LineSessionUpdateOne is the builder for updating a single LineSession entity.
type LineSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LineSessionMutation
}

// SetUpdateAt sets the "update_at" field.
func (lsuo *LineSessionUpdateOne) SetUpdateAt(t time.Time) *LineSessionUpdateOne {
	lsuo.mutation.SetUpdateAt(t)
	return lsuo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (lsuo *LineSessionUpdateOne) SetNillableUpdateAt(t *time.Time) *LineSessionUpdateOne {
	if t != nil {
		lsuo.SetUpdateAt(*t)
	}
	return lsuo
}

// Mutation returns the LineSessionMutation object of the builder.
func (lsuo *LineSessionUpdateOne) Mutation() *LineSessionMutation {
	return lsuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (lsuo *LineSessionUpdateOne) Select(field string, fields ...string) *LineSessionUpdateOne {
	lsuo.fields = append([]string{field}, fields...)
	return lsuo
}

// Save executes the query and returns the updated LineSession entity.
func (lsuo *LineSessionUpdateOne) Save(ctx context.Context) (*LineSession, error) {
	var (
		err  error
		node *LineSession
	)
	if len(lsuo.hooks) == 0 {
		node, err = lsuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LineSessionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lsuo.mutation = mutation
			node, err = lsuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(lsuo.hooks) - 1; i >= 0; i-- {
			if lsuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lsuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lsuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (lsuo *LineSessionUpdateOne) SaveX(ctx context.Context) *LineSession {
	node, err := lsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (lsuo *LineSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := lsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lsuo *LineSessionUpdateOne) ExecX(ctx context.Context) {
	if err := lsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (lsuo *LineSessionUpdateOne) sqlSave(ctx context.Context) (_node *LineSession, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   linesession.Table,
			Columns: linesession.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: linesession.FieldID,
			},
		},
	}
	id, ok := lsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LineSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := lsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linesession.FieldID)
		for _, f := range fields {
			if !linesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != linesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := lsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lsuo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: linesession.FieldUpdateAt,
		})
	}
	_node = &LineSession{config: lsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, lsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
