// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tsukuyomi/ent/linesession"
	"tsukuyomi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineSessionDelete is the builder for deleting a LineSession entity.
type LineSessionDelete struct {
	config
	hooks    []Hook
	mutation *LineSessionMutation
}

// Where appends a list predicates to the LineSessionDelete builder.
func (lsd *LineSessionDelete) Where(ps ...predicate.LineSession) *LineSessionDelete {
	lsd.mutation.Where(ps...)
	return lsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lsd *LineSessionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lsd.hooks) == 0 {
		affected, err = lsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LineSessionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lsd.mutation = mutation
			affected, err = lsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lsd.hooks) - 1; i >= 0; i-- {
			if lsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lsd *LineSessionDelete) ExecX(ctx context.Context) int {
	n, err := lsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lsd *LineSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: linesession.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: linesession.FieldID,
			},
		},
	}
	if ps := lsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, lsd.driver, _spec)
}

// LineSessionDeleteOne is the builder for deleting a single LineSession entity.
type LineSessionDeleteOne struct {
	lsd *LineSessionDelete
}

// Exec executes the deletion query.
func (lsdo *LineSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := lsdo.lsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{linesession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lsdo *LineSessionDeleteOne) ExecX(ctx context.Context) {
	lsdo.lsd.ExecX(ctx)
}
