// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"tsukuyomi/ent/lineuser"
	"tsukuyomi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineUserDelete is the builder for deleting a LineUser entity.
type LineUserDelete struct {
	config
	hooks    []Hook
	mutation *LineUserMutation
}

// Where appends a list predicates to the LineUserDelete builder.
func (lud *LineUserDelete) Where(ps ...predicate.LineUser) *LineUserDelete {
	lud.mutation.Where(ps...)
	return lud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lud *LineUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(lud.hooks) == 0 {
		affected, err = lud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LineUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			lud.mutation = mutation
			affected, err = lud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(lud.hooks) - 1; i >= 0; i-- {
			if lud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = lud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, lud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (lud *LineUserDelete) ExecX(ctx context.Context) int {
	n, err := lud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lud *LineUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: lineuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: lineuser.FieldID,
			},
		},
	}
	if ps := lud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, lud.driver, _spec)
}

// LineUserDeleteOne is the builder for deleting a single LineUser entity.
type LineUserDeleteOne struct {
	lud *LineUserDelete
}

// Exec executes the deletion query.
func (ludo *LineUserDeleteOne) Exec(ctx context.Context) error {
	n, err := ludo.lud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lineuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ludo *LineUserDeleteOne) ExecX(ctx context.Context) {
	ludo.lud.ExecX(ctx)
}
