// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"tsukuyomi/ent/lineuser"
	"tsukuyomi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineUserUpdate is the builder for updating LineUser entities.
type LineUserUpdate struct {
	config
	hooks    []Hook
	mutation *LineUserMutation
}

// Where appends a list predicates to the LineUserUpdate builder.
func (luu *LineUserUpdate) Where(ps ...predicate.LineUser) *LineUserUpdate {
	luu.mutation.Where(ps...)
	return luu
}

// SetIsActive sets the "is_active" field.
func (luu *LineUserUpdate) SetIsActive(b bool) *LineUserUpdate {
	luu.mutation.SetIsActive(b)
	return luu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (luu *LineUserUpdate) SetNillableIsActive(b *bool) *LineUserUpdate {
	if b != nil {
		luu.SetIsActive(*b)
	}
	return luu
}

// SetUpdateAt sets the "update_at" field.
func (luu *LineUserUpdate) SetUpdateAt(t time.Time) *LineUserUpdate {
	luu.mutation.SetUpdateAt(t)
	return luu
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (luu *LineUserUpdate) SetNillableUpdateAt(t *time.Time) *LineUserUpdate {
	if t != nil {
		luu.SetUpdateAt(*t)
	}
	return luu
}

// Mutation returns the LineUserMutation object of the builder.
func (luu *LineUserUpdate) Mutation() *LineUserMutation {
	return luu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (luu *LineUserUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(luu.hooks) == 0 {
		affected, err = luu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LineUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			luu.mutation = mutation
			affected, err = luu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(luu.hooks) - 1; i >= 0; i-- {
			if luu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = luu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, luu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (luu *LineUserUpdate) SaveX(ctx context.Context) int {
	affected, err := luu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (luu *LineUserUpdate) Exec(ctx context.Context) error {
	_, err := luu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luu *LineUserUpdate) ExecX(ctx context.Context) {
	if err := luu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (luu *LineUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lineuser.Table,
			Columns: lineuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: lineuser.FieldID,
			},
		},
	}
	if ps := luu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luu.mutation.IsActive(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: lineuser.FieldIsActive,
		})
	}
	if value, ok := luu.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: lineuser.FieldUpdateAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, luu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lineuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// LineUserUpdateOne is the builder for updating a single LineUser entity.
type LineUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LineUserMutation
}

// SetIsActive sets the "is_active" field.
func (luuo *LineUserUpdateOne) SetIsActive(b bool) *LineUserUpdateOne {
	luuo.mutation.SetIsActive(b)
	return luuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (luuo *LineUserUpdateOne) SetNillableIsActive(b *bool) *LineUserUpdateOne {
	if b != nil {
		luuo.SetIsActive(*b)
	}
	return luuo
}

// SetUpdateAt sets the "update_at" field.
func (luuo *LineUserUpdateOne) SetUpdateAt(t time.Time) *LineUserUpdateOne {
	luuo.mutation.SetUpdateAt(t)
	return luuo
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (luuo *LineUserUpdateOne) SetNillableUpdateAt(t *time.Time) *LineUserUpdateOne {
	if t != nil {
		luuo.SetUpdateAt(*t)
	}
	return luuo
}

// Mutation returns the LineUserMutation object of the builder.
func (luuo *LineUserUpdateOne) Mutation() *LineUserMutation {
	return luuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luuo *LineUserUpdateOne) Select(field string, fields ...string) *LineUserUpdateOne {
	luuo.fields = append([]string{field}, fields...)
	return luuo
}

// Save executes the query and returns the updated LineUser entity.
func (luuo *LineUserUpdateOne) Save(ctx context.Context) (*LineUser, error) {
	var (
		err  error
		node *LineUser
	)
	if len(luuo.hooks) == 0 {
		node, err = luuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LineUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			luuo.mutation = mutation
			node, err = luuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(luuo.hooks) - 1; i >= 0; i-- {
			if luuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = luuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, luuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (luuo *LineUserUpdateOne) SaveX(ctx context.Context) *LineUser {
	node, err := luuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luuo *LineUserUpdateOne) Exec(ctx context.Context) error {
	_, err := luuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luuo *LineUserUpdateOne) ExecX(ctx context.Context) {
	if err := luuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (luuo *LineUserUpdateOne) sqlSave(ctx context.Context) (_node *LineUser, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lineuser.Table,
			Columns: lineuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: lineuser.FieldID,
			},
		},
	}
	id, ok := luuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LineUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lineuser.FieldID)
		for _, f := range fields {
			if !lineuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != lineuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luuo.mutation.IsActive(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: lineuser.FieldIsActive,
		})
	}
	if value, ok := luuo.mutation.UpdateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: lineuser.FieldUpdateAt,
		})
	}
	_node = &LineUser{config: luuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{lineuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
