// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"tsukuyomi/ent/linesession"
	"tsukuyomi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LineSessionQuery is the builder for querying LineSession entities.
type LineSessionQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LineSession
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LineSessionQuery builder.
func (lsq *LineSessionQuery) Where(ps ...predicate.LineSession) *LineSessionQuery {
	lsq.predicates = append(lsq.predicates, ps...)
	return lsq
}

// Limit adds a limit step to the query.
func (lsq *LineSessionQuery) Limit(limit int) *LineSessionQuery {
	lsq.limit = &limit
	return lsq
}

// Offset adds an offset step to the query.
func (lsq *LineSessionQuery) Offset(offset int) *LineSessionQuery {
	lsq.offset = &offset
	return lsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lsq *LineSessionQuery) Unique(unique bool) *LineSessionQuery {
	lsq.unique = &unique
	return lsq
}

// Order adds an order step to the query.
func (lsq *LineSessionQuery) Order(o ...OrderFunc) *LineSessionQuery {
	lsq.order = append(lsq.order, o...)
	return lsq
}

// First returns the first LineSession entity from the query.
// Returns a *NotFoundError when no LineSession was found.
func (lsq *LineSessionQuery) First(ctx context.Context) (*LineSession, error) {
	nodes, err := lsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{linesession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lsq *LineSessionQuery) FirstX(ctx context.Context) *LineSession {
	node, err := lsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LineSession ID from the query.
// Returns a *NotFoundError when no LineSession ID was found.
func (lsq *LineSessionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{linesession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lsq *LineSessionQuery) FirstIDX(ctx context.Context) int {
	id, err := lsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LineSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LineSession entity is found.
// Returns a *NotFoundError when no LineSession entities are found.
func (lsq *LineSessionQuery) Only(ctx context.Context) (*LineSession, error) {
	nodes, err := lsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{linesession.Label}
	default:
		return nil, &NotSingularError{linesession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lsq *LineSessionQuery) OnlyX(ctx context.Context) *LineSession {
	node, err := lsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LineSession ID in the query.
// Returns a *NotSingularError when more than one LineSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (lsq *LineSessionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{linesession.Label}
	default:
		err = &NotSingularError{linesession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lsq *LineSessionQuery) OnlyIDX(ctx context.Context) int {
	id, err := lsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LineSessions.
func (lsq *LineSessionQuery) All(ctx context.Context) ([]*LineSession, error) {
	if err := lsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return lsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (lsq *LineSessionQuery) AllX(ctx context.Context) []*LineSession {
	nodes, err := lsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LineSession IDs.
func (lsq *LineSessionQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := lsq.Select(linesession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lsq *LineSessionQuery) IDsX(ctx context.Context) []int {
	ids, err := lsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lsq *LineSessionQuery) Count(ctx context.Context) (int, error) {
	if err := lsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return lsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (lsq *LineSessionQuery) CountX(ctx context.Context) int {
	count, err := lsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lsq *LineSessionQuery) Exist(ctx context.Context) (bool, error) {
	if err := lsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return lsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (lsq *LineSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := lsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LineSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lsq *LineSessionQuery) Clone() *LineSessionQuery {
	if lsq == nil {
		return nil
	}
	return &LineSessionQuery{
		config:     lsq.config,
		limit:      lsq.limit,
		offset:     lsq.offset,
		order:      append([]OrderFunc{}, lsq.order...),
		predicates: append([]predicate.LineSession{}, lsq.predicates...),
		// clone intermediate query.
		sql:    lsq.sql.Clone(),
		path:   lsq.path,
		unique: lsq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type int8 `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LineSession.Query().
//		GroupBy(linesession.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (lsq *LineSessionQuery) GroupBy(field string, fields ...string) *LineSessionGroupBy {
	group := &LineSessionGroupBy{config: lsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := lsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return lsq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type int8 `json:"type,omitempty"`
//	}
//
//	client.LineSession.Query().
//		Select(linesession.FieldType).
//		Scan(ctx, &v)
//
func (lsq *LineSessionQuery) Select(fields ...string) *LineSessionSelect {
	lsq.fields = append(lsq.fields, fields...)
	return &LineSessionSelect{LineSessionQuery: lsq}
}

func (lsq *LineSessionQuery) prepareQuery(ctx context.Context) error {
	for _, f := range lsq.fields {
		if !linesession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lsq.path != nil {
		prev, err := lsq.path(ctx)
		if err != nil {
			return err
		}
		lsq.sql = prev
	}
	return nil
}

func (lsq *LineSessionQuery) sqlAll(ctx context.Context) ([]*LineSession, error) {
	var (
		nodes = []*LineSession{}
		_spec = lsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LineSession{config: lsq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, lsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lsq *LineSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lsq.querySpec()
	_spec.Node.Columns = lsq.fields
	if len(lsq.fields) > 0 {
		_spec.Unique = lsq.unique != nil && *lsq.unique
	}
	return sqlgraph.CountNodes(ctx, lsq.driver, _spec)
}

func (lsq *LineSessionQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := lsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (lsq *LineSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   linesession.Table,
			Columns: linesession.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: linesession.FieldID,
			},
		},
		From:   lsq.sql,
		Unique: true,
	}
	if unique := lsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linesession.FieldID)
		for i := range fields {
			if fields[i] != linesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lsq *LineSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lsq.driver.Dialect())
	t1 := builder.Table(linesession.Table)
	columns := lsq.fields
	if len(columns) == 0 {
		columns = linesession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lsq.sql != nil {
		selector = lsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lsq.unique != nil && *lsq.unique {
		selector.Distinct()
	}
	for _, p := range lsq.predicates {
		p(selector)
	}
	for _, p := range lsq.order {
		p(selector)
	}
	if offset := lsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LineSessionGroupBy is the group-by builder for LineSession entities.
type LineSessionGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lsgb *LineSessionGroupBy) Aggregate(fns ...AggregateFunc) *LineSessionGroupBy {
	lsgb.fns = append(lsgb.fns, fns...)
	return lsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (lsgb *LineSessionGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := lsgb.path(ctx)
	if err != nil {
		return err
	}
	lsgb.sql = query
	return lsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lsgb *LineSessionGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := lsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (lsgb *LineSessionGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(lsgb.fields) > 1 {
		return nil, errors.New("ent: LineSessionGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := lsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lsgb *LineSessionGroupBy) StringsX(ctx context.Context) []string {
	v, err := lsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lsgb *LineSessionGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linesession.Label}
	default:
		err = fmt.Errorf("ent: LineSessionGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lsgb *LineSessionGroupBy) StringX(ctx context.Context) string {
	v, err := lsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (lsgb *LineSessionGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(lsgb.fields) > 1 {
		return nil, errors.New("ent: LineSessionGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := lsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lsgb *LineSessionGroupBy) IntsX(ctx context.Context) []int {
	v, err := lsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lsgb *LineSessionGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linesession.Label}
	default:
		err = fmt.Errorf("ent: LineSessionGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lsgb *LineSessionGroupBy) IntX(ctx context.Context) int {
	v, err := lsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (lsgb *LineSessionGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(lsgb.fields) > 1 {
		return nil, errors.New("ent: LineSessionGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := lsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lsgb *LineSessionGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := lsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lsgb *LineSessionGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linesession.Label}
	default:
		err = fmt.Errorf("ent: LineSessionGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lsgb *LineSessionGroupBy) Float64X(ctx context.Context) float64 {
	v, err := lsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (lsgb *LineSessionGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(lsgb.fields) > 1 {
		return nil, errors.New("ent: LineSessionGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := lsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lsgb *LineSessionGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := lsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lsgb *LineSessionGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linesession.Label}
	default:
		err = fmt.Errorf("ent: LineSessionGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lsgb *LineSessionGroupBy) BoolX(ctx context.Context) bool {
	v, err := lsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lsgb *LineSessionGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range lsgb.fields {
		if !linesession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lsgb *LineSessionGroupBy) sqlQuery() *sql.Selector {
	selector := lsgb.sql.Select()
	aggregation := make([]string, 0, len(lsgb.fns))
	for _, fn := range lsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(lsgb.fields)+len(lsgb.fns))
		for _, f := range lsgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(lsgb.fields...)...)
}

// LineSessionSelect is the builder for selecting fields of LineSession entities.
type LineSessionSelect struct {
	*LineSessionQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lss *LineSessionSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lss.prepareQuery(ctx); err != nil {
		return err
	}
	lss.sql = lss.LineSessionQuery.sqlQuery(ctx)
	return lss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lss *LineSessionSelect) ScanX(ctx context.Context, v interface{}) {
	if err := lss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lss *LineSessionSelect) Strings(ctx context.Context) ([]string, error) {
	if len(lss.fields) > 1 {
		return nil, errors.New("ent: LineSessionSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lss *LineSessionSelect) StringsX(ctx context.Context) []string {
	v, err := lss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lss *LineSessionSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linesession.Label}
	default:
		err = fmt.Errorf("ent: LineSessionSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lss *LineSessionSelect) StringX(ctx context.Context) string {
	v, err := lss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lss *LineSessionSelect) Ints(ctx context.Context) ([]int, error) {
	if len(lss.fields) > 1 {
		return nil, errors.New("ent: LineSessionSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lss *LineSessionSelect) IntsX(ctx context.Context) []int {
	v, err := lss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lss *LineSessionSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linesession.Label}
	default:
		err = fmt.Errorf("ent: LineSessionSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lss *LineSessionSelect) IntX(ctx context.Context) int {
	v, err := lss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lss *LineSessionSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lss.fields) > 1 {
		return nil, errors.New("ent: LineSessionSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lss *LineSessionSelect) Float64sX(ctx context.Context) []float64 {
	v, err := lss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lss *LineSessionSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linesession.Label}
	default:
		err = fmt.Errorf("ent: LineSessionSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lss *LineSessionSelect) Float64X(ctx context.Context) float64 {
	v, err := lss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lss *LineSessionSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lss.fields) > 1 {
		return nil, errors.New("ent: LineSessionSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lss *LineSessionSelect) BoolsX(ctx context.Context) []bool {
	v, err := lss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lss *LineSessionSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{linesession.Label}
	default:
		err = fmt.Errorf("ent: LineSessionSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lss *LineSessionSelect) BoolX(ctx context.Context) bool {
	v, err := lss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lss *LineSessionSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lss.sql.Query()
	if err := lss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
