// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"tsukuyomi/ent/linesession"

	"entgo.io/ent/dialect/sql"
)

// LineSession is the model entity for the LineSession schema.
type LineSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type int8 `json:"type,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID string `json:"group_id,omitempty"`
	// RoomID holds the value of the "room_id" field.
	RoomID string `json:"room_id,omitempty"`
	// CreateAt holds the value of the "create_at" field.
	CreateAt time.Time `json:"create_at,omitempty"`
	// UpdateAt holds the value of the "update_at" field.
	UpdateAt time.Time `json:"update_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LineSession) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case linesession.FieldID, linesession.FieldType:
			values[i] = new(sql.NullInt64)
		case linesession.FieldUserID, linesession.FieldGroupID, linesession.FieldRoomID:
			values[i] = new(sql.NullString)
		case linesession.FieldCreateAt, linesession.FieldUpdateAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type LineSession", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LineSession fields.
func (ls *LineSession) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case linesession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ls.ID = int(value.Int64)
		case linesession.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				ls.Type = int8(value.Int64)
			}
		case linesession.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ls.UserID = value.String
			}
		case linesession.FieldGroupID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				ls.GroupID = value.String
			}
		case linesession.FieldRoomID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field room_id", values[i])
			} else if value.Valid {
				ls.RoomID = value.String
			}
		case linesession.FieldCreateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_at", values[i])
			} else if value.Valid {
				ls.CreateAt = value.Time
			}
		case linesession.FieldUpdateAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_at", values[i])
			} else if value.Valid {
				ls.UpdateAt = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this LineSession.
// Note that you need to call LineSession.Unwrap() before calling this method if this LineSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (ls *LineSession) Update() *LineSessionUpdateOne {
	return (&LineSessionClient{config: ls.config}).UpdateOne(ls)
}

// Unwrap unwraps the LineSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ls *LineSession) Unwrap() *LineSession {
	tx, ok := ls.config.driver.(*txDriver)
	if !ok {
		panic("ent: LineSession is not a transactional entity")
	}
	ls.config.driver = tx.drv
	return ls
}

// String implements the fmt.Stringer.
func (ls *LineSession) String() string {
	var builder strings.Builder
	builder.WriteString("LineSession(")
	builder.WriteString(fmt.Sprintf("id=%v", ls.ID))
	builder.WriteString(", type=")
	builder.WriteString(fmt.Sprintf("%v", ls.Type))
	builder.WriteString(", user_id=")
	builder.WriteString(ls.UserID)
	builder.WriteString(", group_id=")
	builder.WriteString(ls.GroupID)
	builder.WriteString(", room_id=")
	builder.WriteString(ls.RoomID)
	builder.WriteString(", create_at=")
	builder.WriteString(ls.CreateAt.Format(time.ANSIC))
	builder.WriteString(", update_at=")
	builder.WriteString(ls.UpdateAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LineSessions is a parsable slice of LineSession.
type LineSessions []*LineSession

func (ls LineSessions) config(cfg config) {
	for _i := range ls {
		ls[_i].config = cfg
	}
}
