// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"
	"tsukuyomi/ent/lineuser"
	"tsukuyomi/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	lineuserFields := schema.LineUser{}.Fields()
	_ = lineuserFields
	// lineuserDescIsActive is the schema descriptor for is_active field.
	lineuserDescIsActive := lineuserFields[1].Descriptor()
	// lineuser.DefaultIsActive holds the default value on creation for the is_active field.
	lineuser.DefaultIsActive = lineuserDescIsActive.Default.(bool)
	// lineuserDescCreateAt is the schema descriptor for create_at field.
	lineuserDescCreateAt := lineuserFields[2].Descriptor()
	// lineuser.DefaultCreateAt holds the default value on creation for the create_at field.
	lineuser.DefaultCreateAt = lineuserDescCreateAt.Default.(func() time.Time)
	// lineuserDescUpdateAt is the schema descriptor for update_at field.
	lineuserDescUpdateAt := lineuserFields[3].Descriptor()
	// lineuser.DefaultUpdateAt holds the default value on creation for the update_at field.
	lineuser.DefaultUpdateAt = lineuserDescUpdateAt.Default.(func() time.Time)
	// lineuserDescID is the schema descriptor for id field.
	lineuserDescID := lineuserFields[0].Descriptor()
	// lineuser.IDValidator is a validator for the "id" field. It is called by the builders before save.
	lineuser.IDValidator = func() func(string) error {
		validators := lineuserDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
