# prod.toml app configuration file generated for tsukuyomi on 2023-05-26T15:43:02+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tsukuyomi"
primary_region = "nrt"

[env]
  VERSION = "0.0.1"
  ENV = "production"
  PORT = 8080

[[services]]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [services.concurrency]
    type = "connections"
    soft_limit = 1
    hard_limit = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "10s"
    grace_period = "30s"
    method = "get"
    protocol = "http"
    path = "/version"
    port = 8080
    timeout = "30s"
    restart_limit = 10
